-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the Wheelyjoe's Weapons Damage Mod updated by Ghosti to support cluster munitions
--
-- This configuration is tailored for a mission generated by DCS Liberation
-- see https://github.com/dcs-liberation/dcs_liberation
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- SplashDamage plugin - configuration
env.info("DCSLiberation|SplashDamage plugin - configuration")

if dcsLiberation then
    env.info("DCSLiberation|SplashDamage plugin - dcsLiberation")

    -- specific options
    local clusterEffects = false

    -- retrieve specific options values
    if dcsLiberation.plugins then
        env.info("DCSLiberation|SplashDamage plugin - dcsLiberation.plugins")
    
        if dcsLiberation.plugins.splashdamage then
            env.info("DCSLiberation|SplashDamage plugin - dcsLiberation.plugins.SplashDamage")
            clusterEffects = dcsLiberation.plugins.splashdamage.clusterEffects
            env.info(string.format("DCSLiberation|SplashDamage plugin - clusterEffects = %s",tostring(clusterEffects)))
        end
    end
    
    -- actual configuration code    
    weaponDamage(clusterEffects)

end