---
name: Syria - Battle for Golan Heights (Skynet by Config)
theater: Syria
authors: Khopa
recommended_player_faction: Israel 2000
recommended_enemy_faction: Syria 2011
description: <p>In this scenario, you start in Israel and the conflict is focused around the golan heights, an historically disputed territory.<br/><br/>This scenario is designed to be performance and helicopter friendly.</p>
miz: golan_heights_skynet.miz
performance: 1
version: "9.2"
advanced_iads: true # Campaign has connection_nodes / power_sources / command_centers
iads:
  Sam:
    - name: Golan North-100
      connected:
        - IADS_CN8
        - IADS_PS4
        - IADS_PS3
    - name: Golan North-11
      connected:
    - name: Golan North-139
      connected:
    - name: Golan North-14
      connected:
    - name: Golan North-140
      connected:
    - name: Golan North-146
      connected:
    - name: Golan North-15
      connected:
    - name: Golan North-150
      connected:
    - name: Golan North-158
      connected:
    - name: Golan North-159
      connected:
    - name: Golan North-17
      connected:
    - name: Golan North-5
      connected:
    - name: Golan North-6
      connected:
        - IADS_PS4
        - IADS_CN7
        - IADS_CN8
    - name: Golan North-74
      connected:
    - name: Golan North-81
      connected:
    - name: Golan North-84
      connected:
    - name: Golan North-88
      connected:
    - name: Golan North-9
      connected:
    - name: Golan North-99 #Medium
      connected:
        - IADS_PS4
        - IADS_CN7
        - IADS_CN8
  Ewr:
    - name: Golan North-118
      connected:
        - IADS_PS4
        - IADS_CN7
        - IADS_CN8
    - name: Golan North-119
      connected:
    - name: Golan North-122
      connected:
  CommandCenter:
    - name: IADS_CC1
      connected:
        -
    - name: IADS_CC2
      connected:
        - IADS_PS3
        - IADS_CN9
        - IADS_CN8
squadrons:
  # Ramat-David
  30:
    - primary: AEW&C
      aircraft:
        - E-3A
    - primary: Refueling
      aircraft:
        - KC-135 Stratotanker
    - primary: Transport
      aircraft:
        - C-130
    - primary: BARCAP
      secondary: any
      aircraft:
        - F-15C Eagle
    - primary: BARCAP
      secondary: any
      aircraft:
        - F-4E Phantom II
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - F-15E Strike Eagle
    - primary: SEAD
      secondary: any
      aircraft:
        - F-16CM Fighting Falcon (Block 50)
  # Golan South
  Golan South:
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - AH-1W SuperCobra
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - AH-64D Apache Longbow
    - primary: Transport
      aircraft:
        - UH-1H Iroquois
  # Golan North
  Golan North:
    - primary: CAS
      secondary: air-to-ground
      aircraft:
        - Mi-24P Hind-F
    - primary: CAS
      aircraft:
        - SA 342M Gazelle
    - primary: Transport
      secondary: air-to-ground
      aircraft:
        - Mi-8MTV2 Hip
  # Marj Ruhayyil
  23:
    - primary: BARCAP
      secondary: any
      aircraft:
        - MiG-21bis Fishbed-N
    - primary: BARCAP
      secondary: any
      aircraft:
        - MiG-23MLD Flogger-K
    - primary: SEAD
      secondary: air-to-ground
      aircraft:
        - Su-17M4 Fitter-K
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - Su-17M4 Fitter-K
  # Damascus
  7:
    - primary: BARCAP
      secondary: any
      aircraft:
        - MiG-29S Fulcrum-C
    - primary: BARCAP
      secondary: any
      aircraft:
        - MiG-21bis Fishbed-N
    - primary: BARCAP
      secondary: any
      aircraft:
        - MiG-25PD Foxbat-E
    - primary: SEAD
      secondary: air-to-ground
      aircraft:
        - Su-24M Fencer-D
    - primary: Strike
      secondary: air-to-ground
      aircraft:
        - Su-17M4 Fitter-K
