-------------------------------------------------------------------------------------------------------------------------------------------------------------
-- configuration file for the LotATC Export script
--
-- This configuration is tailored for a mission generated by DCS Liberation
-- see https://github.com/Khopa/dcs_liberation
-------------------------------------------------------------------------------------------------------------------------------------------------------------

-- LotATC Export plugin - configuration
env.info("DCSLiberation|LotATC Export plugin - configuration")

if dcsLiberation then
    env.info("DCSLiberation|LotATC Export plugin - configuration dcsLiberation")

    local exportRedAA = true
    local exportBlueAA = false
    local exportSymbols = true

    -- retrieve specific options values
    if dcsLiberation.plugins then
        env.info("DCSLiberation|LotATC Export plugin - configuration dcsLiberation.plugins")
    
        if dcsLiberation.plugins.lotatc then
            env.info("DCSLiberation|LotATC Export plugin - dcsLiberation.plugins.lotatcExport")

            exportRedAA = dcsLiberation.plugins.lotatc.exportRedAA
            env.info(string.format("DCSLiberation|LotATC Export plugin - exportRedAA = %s",tostring(exportRedAA)))

            exportBlueAA = dcsLiberation.plugins.lotatc.exportBlueAA
            env.info(string.format("DCSLiberation|LotATC Export plugin - exportBlueAA = %s",tostring(exportBlueAA)))

            exportBlueAA = dcsLiberation.plugins.lotatc.exportSymbols
            env.info(string.format("DCSLiberation|LotATC Export plugin - exportSymbols = %s",tostring(exportSymbols)))
        end
    end
    
    -- actual configuration code
    if LotAtcExportConfig then 
        LotAtcExportConfig.exportRedAA = exportRedAA
        LotAtcExportConfig.exportBlueAA = exportBlueAA
        LotAtcExportConfig.exportSymbols = exportSymbols

        LotatcExport()
    end

end