# DO NOT EDIT:
# This file is generated by resources/tools/export_coordinates.py.
from game.theater.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=33,
    false_easting=-99516.9999999732,
    false_northing=-4998114.999999984,
    scale_factor=0.9996,
)
