# DO NOT EDIT:
# This file is generated by resources/tools/export_coordinates.py.
from game.theater.projections import TransverseMercator

PARAMETERS = TransverseMercator(
    central_meridian=-117,
    false_easting=-193996.80999964548,
    false_northing=-4410028.063999966,
    scale_factor=0.9996,
)
