name: Python lint

on: workflow_call

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@stable
        with:
          version: ~=22.12
          src: "."
          options: "--check"

  mypy:
    name: Type checking
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Python environment
        uses: ./.github/actions/setup-liberation-python

      - name: mypy
        uses: ./.github/actions/mypy
